version: '3'
services:
  web:
    build: .
    ports:
      - "3040:3000"
      # - "9229:9229"
    command: ./node_modules/nodemon/bin/nodemon.js
    volumes:
      - .:/data
      - $HOME/.aws:/root/.aws
    working_dir: /data
    environment:
      - NODE_ENV=development
      - AWS_PROFILE=saml
  db:
    image: mysql:5.7
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      